require: standard

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "bin/*"
    - "vendor/**/*"
    - "Gemfile"
  TargetRubyVersion: 3.4
