module Tantiny
  class TantivyError < StandardError
  end

  class UnknownField < StandardError
    def initialize: () -> void
  end

  class UnknownTokenizer < StandardError
    def initialize: (Symbol tokenizer_type) -> void
  end

  class UnsupportedRange < StandardError
    def initialize: (Class range_type) -> void
  end

  class UnsupportedField < StandardError
    def initialize: (Symbol field) -> void
  end
end
