module Tantiny
  class Tokenizer
    def self.default: () -> Tokenizer

    def self.new: (Symbol kind, **untyped options) -> Tokenizer

    def self.__new_ngram_tokenizer: (
      Integer min,
      Integer max,
      bool prefix_only
    ) -> Tokenizer

    def self.__new_stemmer_tokenizer: (
      String locale_code
    ) -> Tokenizer

    def self.__new_simple_tokenizer: () -> Tokenizer

    public

    def terms: (String string) -> Array[String]

    def __extract_terms: (String string) -> Array[String]
  end
end
