require "thermite/tasks"

project_dir = File.dirname(File.dirname(__FILE__)) # rubocop:disable Style/NestedFileDirname
Thermite::Tasks.new(cargo_project_path: project_dir, ruby_project_path: project_dir)
task default: %w[thermite:build]
